### ISSUE TITLE
Static layout

### ISSUE THREAD

**Issue by surbhitt** [surbhitt/group-portfolio#2]

**Comment by triptisingla** [comment]
added static layout
![Screenshot 2024-04-27 141342](https://github.com/surbhitt/group-portfolio/assets/66973531/5e9739e0-615b-47f0-8f62-0922e1f4340d)
![Screenshot 2024-04-27 141323](https://github.com/surbhitt/group-portfolio/assets/66973531/58e059cf-f897-476d-9333-f22ae11f2a44)
